//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpFetch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpFetch.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompt.
        /// </summary>
        internal static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cores.
        /// </summary>
        internal static string CPUCoresFormat {
            get {
                return ResourceManager.GetString("CPUCoresFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid locale '{0}'. Using default locale..
        /// </summary>
        internal static string ErrorInvalidLocale {
            get {
                return ResourceManager.GetString("ErrorInvalidLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: --locale requires a value (e.g., en-US, es-ES).
        /// </summary>
        internal static string ErrorMissingLocaleValue {
            get {
                return ResourceManager.GetString("ErrorMissingLocaleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown option '{0}'.
        /// </summary>
        internal static string ErrorUnknownOption {
            get {
                return ResourceManager.GetString("ErrorUnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cross-platform system information utility similar to neofetch..
        /// </summary>
        internal static string HelpDescription {
            get {
                return ResourceManager.GetString("HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sharpfetch           Show system info in default language.
        /// </summary>
        internal static string HelpExampleDefault {
            get {
                return ResourceManager.GetString("HelpExampleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sharpfetch --locale es-ES    Show system info in Spanish.
        /// </summary>
        internal static string HelpExampleSpanish {
            get {
                return ResourceManager.GetString("HelpExampleSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        internal static string HelpExamples {
            get {
                return ResourceManager.GetString("HelpExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --help               Show this help message.
        /// </summary>
        internal static string HelpHelpOption {
            get {
                return ResourceManager.GetString("HelpHelpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --locale &lt;locale&gt;    Set the display language (e.g., en-US, es-ES).
        /// </summary>
        internal static string HelpLocaleOption {
            get {
                return ResourceManager.GetString("HelpLocaleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string HelpOptions {
            get {
                return ResourceManager.GetString("HelpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: sharpfetch [OPTIONS].
        /// </summary>
        internal static string HelpUsage {
            get {
                return ResourceManager.GetString("HelpUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --version            Show version information.
        /// </summary>
        internal static string HelpVersionOption {
            get {
                return ResourceManager.GetString("HelpVersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors:.
        /// </summary>
        internal static string LabelColors {
            get {
                return ResourceManager.GetString("LabelColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU:.
        /// </summary>
        internal static string LabelCPU {
            get {
                return ResourceManager.GetString("LabelCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET:.
        /// </summary>
        internal static string LabelDotNet {
            get {
                return ResourceManager.GetString("LabelDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel:.
        /// </summary>
        internal static string LabelKernel {
            get {
                return ResourceManager.GetString("LabelKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory:.
        /// </summary>
        internal static string LabelMemory {
            get {
                return ResourceManager.GetString("LabelMemory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network:.
        /// </summary>
        internal static string LabelNetwork {
            get {
                return ResourceManager.GetString("LabelNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OS:.
        /// </summary>
        internal static string LabelOS {
            get {
                return ResourceManager.GetString("LabelOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell:.
        /// </summary>
        internal static string LabelShell {
            get {
                return ResourceManager.GetString("LabelShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal:.
        /// </summary>
        internal static string LabelTerminal {
            get {
                return ResourceManager.GetString("LabelTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime:.
        /// </summary>
        internal static string LabelUptime {
            get {
                return ResourceManager.GetString("LabelUptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to macOS.
        /// </summary>
        internal static string MacOSDefault {
            get {
                return ResourceManager.GetString("MacOSDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to macOS {0}.
        /// </summary>
        internal static string MacOSFormat {
            get {
                return ResourceManager.GetString("MacOSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string MemoryUsageFormat {
            get {
                return ResourceManager.GetString("MemoryUsageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell.
        /// </summary>
        internal static string PowerShell {
            get {
                return ResourceManager.GetString("PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days, {1} hours, {2} mins.
        /// </summary>
        internal static string UptimeDaysHoursMinutes {
            get {
                return ResourceManager.GetString("UptimeDaysHoursMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours, {1} mins.
        /// </summary>
        internal static string UptimeHoursMinutes {
            get {
                return ResourceManager.GetString("UptimeHoursMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins.
        /// </summary>
        internal static string UptimeMinutes {
            get {
                return ResourceManager.GetString("UptimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpFetch v1.0.0 - A cross-platform system information utility.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string WindowsDefault {
            get {
                return ResourceManager.GetString("WindowsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows {0}.{1} (Build {2}).
        /// </summary>
        internal static string WindowsOSFormat {
            get {
                return ResourceManager.GetString("WindowsOSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Terminal.
        /// </summary>
        internal static string WindowsTerminal {
            get {
                return ResourceManager.GetString("WindowsTerminal", resourceCulture);
            }
        }
    }
}